"""Configuration for the content pipeline.

All settings live in ``content_pipeline.yaml`` at the repo root, with
secrets (API keys/tokens) read from the environment / ``.env`` so the
YAML file is safe to commit.
"""

import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional

from .trends import ResearchConfig

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CONFIG_PATH = PROJECT_ROOT / "content_pipeline.yaml"


@dataclass
class AffiliateProduct:
    """A product/service we link to for affiliate revenue."""

    name: str
    url: str
    blurb: str
    keywords: List[str] = field(default_factory=list)


@dataclass
class MonetizationConfig:
    newsletter_cta: str = ""
    newsletter_signup_url: str = ""
    premium_cta: str = ""
    premium_url: str = ""
    sponsor_slot: str = ""  # empty = no sponsor booked
    affiliates: List[AffiliateProduct] = field(default_factory=list)
    utm_source: str = "content-engine"
    disclaimer: str = (
        "This content is generated by an automated research system and is "
        "for informational and educational purposes only. It is not "
        "professional or financial advice. Do your own research."
    )


@dataclass
class BrandConfig:
    name: str = "Content Engine"
    tagline: str = "Automated daily intelligence."
    # What the content is about — drives the LLM's system prompt. E.g.
    # "an automated quant trading strategy's daily signals" or
    # "developments in open-source AI tooling".
    subject: str = "the day's developments in your niche"
    voice: str = (
        "Confident, data-driven, concise. Explains concepts in plain "
        "English. Never hypes, never overpromises."
    )
    site_url: str = ""
    author: str = "Content Engine Bot"


@dataclass
class PersonaConfig:
    """Optional AI-influencer persona for character-consistent visuals.
    Leave ``name`` empty to disable. Injected into image/video prompts
    (the 'consistency block') and the LLM's voice."""

    name: str = ""
    appearance: str = ""   # e.g. "mid-20s woman, warm smile, hazel eyes"
    wardrobe: str = ""     # e.g. "minimal neutral knitwear, gold jewelry"
    setting: str = ""      # e.g. "sunlit loft apartment, plants, soft bokeh"
    style: str = ""        # e.g. "aspirational, relatable, premium"

    @property
    def enabled(self) -> bool:
        return bool(self.name)

    def consistency_block(self) -> str:
        """Copy-paste block that keeps the character identical across
        image/video generations."""
        parts = [f"Character: {self.name}"]
        if self.appearance:
            parts.append(f"appearance: {self.appearance}")
        if self.wardrobe:
            parts.append(f"wardrobe: {self.wardrobe}")
        if self.setting:
            parts.append(f"setting: {self.setting}")
        parts.append("same face, same styling, consistent identity across all shots")
        return "; ".join(parts)


@dataclass
class SourceConfig:
    """Where the day's facts come from.

    - ``market``: free index data (Stooq, no key) plus, when configured,
      any trading system's state — a trades/positions JSON and a
      directory of target-weight CSVs (see docs for the format).
    - ``custom``: facts from a YAML/JSON file that you (or another job)
      write, so any niche can drive the engine.
    """

    type: str = "market"  # 'market' | 'custom'
    # market source (all optional; env vars override)
    trades_file: str = ""   # SOURCE_TRADES_FILE — trades/positions state JSON
    weights_dir: str = ""   # SOURCE_WEIGHTS_DIR — target-weight CSVs (latest used)
    # custom source
    facts_file: str = ""    # SOURCE_FACTS_FILE — {headline: str, facts: [str,...]}

    def resolved_trades_file(self) -> Optional[Path]:
        raw = os.getenv("SOURCE_TRADES_FILE", self.trades_file)
        return Path(raw).expanduser() if raw else None

    def resolved_weights_dir(self) -> Optional[Path]:
        raw = os.getenv("SOURCE_WEIGHTS_DIR", self.weights_dir)
        return Path(raw).expanduser() if raw else None

    def resolved_facts_file(self) -> Optional[Path]:
        raw = os.getenv("SOURCE_FACTS_FILE", self.facts_file)
        return Path(raw).expanduser() if raw else None


@dataclass
class LLMConfig:
    # Provider preference order; each is skipped if its key is missing.
    anthropic_model: str = "claude-sonnet-5"
    openai_model: str = "gpt-4o-mini"
    max_tokens: int = 2000
    temperature: float = 0.7
    request_timeout: int = 60

    @property
    def anthropic_api_key(self) -> Optional[str]:
        return os.getenv("ANTHROPIC_API_KEY") or None

    @property
    def openai_api_key(self) -> Optional[str]:
        key = os.getenv("OPENAI_API_KEY", "")
        # ignore placeholder values from .env.example
        return key if key and not key.startswith("your_") else None


@dataclass
class MediaConfig:
    enable_images: bool = True
    enable_video: bool = True
    # Extra AI hero image via OpenAI's image API when a key is present.
    use_ai_images: bool = False
    openai_image_model: str = "gpt-image-1"
    # TTS tiers (used for the daily short's voiceover)
    elevenlabs_voice_id: str = "21m00Tcm4TlvDq8ikWAM"  # 'Rachel'
    openai_tts_model: str = "gpt-4o-mini-tts"
    openai_tts_voice: str = "onyx"
    # Rendering
    image_size: List[int] = field(default_factory=lambda: [1080, 1080])
    video_size: List[int] = field(default_factory=lambda: [1080, 1920])
    seconds_per_slide: int = 6
    # Optional Replicate model for AI video (documented, off by default)
    replicate_video_model: str = ""


@dataclass
class ChannelConfig:
    """Which content types go to which channels."""

    daily_brief: List[str] = field(
        default_factory=lambda: ["blog", "telegram", "discord"]
    )
    social_thread: List[str] = field(default_factory=lambda: ["twitter", "telegram"])
    newsletter: List[str] = field(default_factory=lambda: ["buttondown", "blog"])
    video_script: List[str] = field(default_factory=lambda: ["blog"])
    # Internal working doc — saved to content/generated; add "blog" to publish.
    production_pack: List[str] = field(default_factory=list)


# Serverless platforms (e.g. Vercel) only allow writes under /tmp.
# Setting CONTENT_DATA_DIR relocates every writable path there.
_DATA_ROOT = Path(os.getenv("CONTENT_DATA_DIR") or PROJECT_ROOT)


@dataclass
class PipelineConfig:
    brand: BrandConfig = field(default_factory=BrandConfig)
    persona: PersonaConfig = field(default_factory=PersonaConfig)
    source: SourceConfig = field(default_factory=SourceConfig)
    research: ResearchConfig = field(default_factory=ResearchConfig)
    llm: LLMConfig = field(default_factory=LLMConfig)
    monetization: MonetizationConfig = field(default_factory=MonetizationConfig)
    channels: ChannelConfig = field(default_factory=ChannelConfig)
    media: MediaConfig = field(default_factory=MediaConfig)
    output_dir: Path = _DATA_ROOT / "content" / "generated"
    blog_dir: Path = _DATA_ROOT / "content" / "posts"
    ledger_path: Path = _DATA_ROOT / "data" / "content_ledger.json"
    # Weekday (0=Mon .. 6=Sun) on which the weekly newsletter goes out.
    newsletter_weekday: int = 6


def load_pipeline_config(path: Optional[Path] = None) -> PipelineConfig:
    """Load config from YAML, falling back to sane defaults for any
    missing section so a bare repo still runs."""
    path = Path(path) if path else DEFAULT_CONFIG_PATH
    cfg = PipelineConfig()
    if not path.exists():
        return cfg

    raw = yaml.safe_load(path.read_text()) or {}

    for section_name, target in (
        ("brand", cfg.brand),
        ("persona", cfg.persona),
        ("source", cfg.source),
        ("research", cfg.research),
    ):
        for k, v in raw.get(section_name, {}).items():
            if hasattr(target, k):
                setattr(target, k, v)

    llm = raw.get("llm", {})
    for k, v in llm.items():
        if hasattr(cfg.llm, k) and not isinstance(getattr(LLMConfig, k, None), property):
            setattr(cfg.llm, k, v)

    mon = raw.get("monetization", {})
    for k, v in mon.items():
        if k == "affiliates":
            cfg.monetization.affiliates = [
                AffiliateProduct(
                    name=a.get("name", ""),
                    url=a.get("url", ""),
                    blurb=a.get("blurb", ""),
                    keywords=a.get("keywords", []),
                )
                for a in (v or [])
            ]
        elif hasattr(cfg.monetization, k):
            setattr(cfg.monetization, k, v)

    ch = raw.get("channels", {})
    for k, v in ch.items():
        if hasattr(cfg.channels, k):
            setattr(cfg.channels, k, list(v))

    media = raw.get("media", {})
    for k, v in media.items():
        if hasattr(cfg.media, k):
            setattr(cfg.media, k, v)

    if "newsletter_weekday" in raw:
        cfg.newsletter_weekday = int(raw["newsletter_weekday"])
    if "output_dir" in raw:
        cfg.output_dir = PROJECT_ROOT / raw["output_dir"]
    if "blog_dir" in raw:
        cfg.blog_dir = PROJECT_ROOT / raw["blog_dir"]

    return cfg
