"""Daily portfolio report generator."""

from __future__ import annotations

from datetime import datetime, timedelta
from typing import Optional

from ..models import PortfolioState
from .common import fmt_money, fmt_signed_money, positions_table, trades_table


def generate_daily_report(
    state: PortfolioState, as_of: Optional[datetime] = None
) -> str:
    as_of = as_of or datetime.now()
    day_start = as_of.replace(hour=0, minute=0, second=0, microsecond=0)
    todays_trades = state.trades_between(start=day_start, end=as_of)

    change = state.equity_change()
    change_line = (
        f"**Change since last snapshot:** {fmt_signed_money(change)}"
        if change is not None
        else "**Change since last snapshot:** n/a (not enough history)"
    )

    invested = state.equity - state.cash
    agent = "running" if state.agent_running else "stopped"

    return f"""# Daily Trading Report — {as_of:%Y-%m-%d}

## Portfolio Snapshot

- **Total equity:** {fmt_money(state.equity)}
- **Cash:** {fmt_money(state.cash)}
- **Invested:** {fmt_money(invested)}
- **Agent status:** {agent}

{change_line}

## Open Positions

{positions_table(state.positions)}

## Today's Trades ({len(todays_trades)})

{trades_table(todays_trades)}

---
*Generated by Maxtrader Content Engine at {as_of:%Y-%m-%d %H:%M}. Not investment advice.*
"""
