"""Weekly performance review generator."""

from __future__ import annotations

from collections import Counter
from datetime import datetime, timedelta
from typing import Optional

from ..models import PortfolioState
from .common import fmt_money, fmt_signed_money, positions_table, trades_table


def generate_weekly_review(
    state: PortfolioState, as_of: Optional[datetime] = None
) -> str:
    as_of = as_of or datetime.now()
    week_start = as_of - timedelta(days=7)
    week_trades = state.trades_between(start=week_start, end=as_of)

    buys = [t for t in week_trades if t.action == "buy"]
    sells = [t for t in week_trades if t.action == "sell"]
    buy_notional = sum(t.notional for t in buys)
    sell_notional = sum(t.notional for t in sells)
    most_traded = Counter(t.ticker for t in week_trades).most_common(3)
    most_traded_str = (
        ", ".join(f"{tk} ({n})" for tk, n in most_traded) if most_traded else "—"
    )

    week_points = [
        p for p in state.equity_curve if p.timestamp and p.timestamp >= week_start
    ]
    if len(week_points) >= 2:
        week_change = week_points[-1].equity - week_points[0].equity
        pct = (week_change / week_points[0].equity * 100.0) if week_points[0].equity else 0.0
        perf_line = f"Equity moved {fmt_signed_money(week_change)} ({pct:+.2f}%) over the week."
    else:
        perf_line = "Not enough equity history this week to compute performance."

    return f"""# Weekly Review — week ending {as_of:%Y-%m-%d}

## Performance

{perf_line}

- **Current equity:** {fmt_money(state.equity)}
- **Cash:** {fmt_money(state.cash)}

## Activity

- **Trades:** {len(week_trades)} ({len(buys)} buys / {len(sells)} sells)
- **Bought:** {fmt_money(buy_notional)} · **Sold:** {fmt_money(sell_notional)}
- **Most traded:** {most_traded_str}

## Trades This Week

{trades_table(week_trades)}

## Positions Going Into Next Week

{positions_table(state.positions)}

---
*Generated by Maxtrader Content Engine at {as_of:%Y-%m-%d %H:%M}. Not investment advice.*
"""
